[build]
command = "npm run build"
publish = "./public" # Change this if your static files are in a different directory

[functions]
directory = "netlify-functions" # Create this directory in your project

[build.environment]
BARD_API_KEY = "$BARD_API_KEY" # This links to your environment variable in Netlify

[build.processing]
skip_processing = "**/*.[sS]h"
